services:
  goshort-db:
    image: postgres
    restart: always
    container_name: goshort-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - goshort_data:/var/lib/postgresql/data

volumes:
  goshort_data:
